### ISSUE TITLE
How to make storage persistent with docker?

### ISSUE THREAD

**Issue by billyjacoby** [staticdeploy/staticdeploy#59]
I'm loving the potential for this project, however I can't seem to figure out where exactly all of the assets are stored in the docker container.

I'm trying to figure out where to mount a persistent storage volume to achieve this, could someone point me in the right direction?

Thanks!

**Comment by pscanf** [comment]
Hey @billyjacoby, nice to hear that. 🙂

There are currently two _storage backends_ supported by StaticDeploy:

- in-memory storage ([implemented here](https://github.com/staticdeploy/staticdeploy/tree/master/memory-storages)), which stores everything in memory and is therefore ephemeral
- Postrgres + S3 storage ([implemented here](https://github.com/staticdeploy/staticdeploy/tree/master/pg-s3-storages)), which stores metadata in a Postgres database, and assets in an S3-compatible storage

When you start a `staticdeploy/staticdeploy` image, if you provide [environment variables for connecting to a Postgres database and an S3-compatible storage](https://staticdeploy.io/docs/guides-deploying-staticdeploy-with-docker#pg-s3-storages-configurations), the Postgres + S3 storage will be used. Otherwise, the in-memory storage will be used.

The in-memory storage is mostly used for testing and to power the side-project [app-server](https://github.com/staticdeploy/app-server), so if you want to run the **StaticDeploy platform** you'll need to use the Postgres + S3 storage, for which you need to have a running Postgres and either and an S3-compatible storage like [MinIO](https://min.io/) (or, of course, S3).

For HA deployments of StaticDeploy I usually go with _managed services_, like AWS RDS and S3. For non-mission-critical deployments, like the one that serves [staticdeploy.io](https://staticdeploy.io/) and my personal website, I have a simpler set-up that uses docker-compose to bring up `postgres`, `minio/minio`, and `staticdeploy/staticdeploy` in a single VM. I can share the `docker-compose.yml` if you're interested.

**Comment by billyjacoby** [comment]
Yeahhh that's what i figured when taking a look at everything. I was hoping I was missing something though.

I think it would be beneficial to add a local storage option, but I'm not sure how I would implement this myself.

**Comment by pscanf** [comment]
You mean like a filesystem storage? With the docker-compose approach ultimately things end up on the filesystem, though "locked" in the formats that Postgres and MinIO use to persist data.

It would be also quite easy (basically just copying [memory-storages](https://github.com/staticdeploy/staticdeploy/tree/master/memory-storages)) to implement a `fs-storages` module that - for example - could store everything in json files. Unfortunately at the moment I don't have the time to do that, but if you want to give it a go I can help you out understanding how to do it.

**Comment by billyjacoby** [comment]
I'm just talking about the `fs-storages` option. If i have some free time later today i'll take a look and see if i can figure out how to write from memory-storages, then subsequently check if any data is there to load upon starting.

**Comment by pscanf** [comment]
Sure. Feel free to ask if you need help. There's already a suite of tests for the storages interface, so it should be just a matter of implementing the ~50 methods of the interface until all tests pass.

**Comment by brumar** [comment]
I'd like to view your docker-compose.yaml file. That would same me time (and maybe others too!).
Thank you so much for this work, I love it !

**Comment by pscanf** [comment]
Hey @brumar ,

here it is:

```yml
version: "3"
services:
  staticdeploy:
    image: staticdeploy/staticdeploy:$STATICDEPLOY_VERSION
    restart: always
    depends_on:
      - postgres
      - minio
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=HostRegexp:{host:.*}
      - traefik.frontend.passHostHeader=true
      - traefik.frontend.entryPoints=http,https
    environment:
      - MANAGEMENT_HOSTNAME=$MANAGEMENT_HOSTNAME
      - JWT_SECRET_OR_PUBLIC_KEY=$JWT_SECRET_OR_PUBLIC_KEY
      - OIDC_CONFIGURATION_URL=$OIDC_CONFIGURATION_URL
      - OIDC_CLIENT_ID=$OIDC_CLIENT_ID
      - OIDC_PROVIDER_NAME=$OIDC_PROVIDER_NAME
      - POSTGRES_URL=postgres://postgres:$POSTGRES_PASSWORD@postgres/postgres
      - S3_BUCKET=staticdeploy
      - S3_ENDPOINT=http://minio:9000
      - S3_ACCESS_KEY_ID=$MINIO_ACCESS_KEY
      - S3_SECRET_ACCESS_KEY=$MINIO_SECRET_KEY

  postgres:
    image: postgres
    restart: always
    labels:
      - traefik.enable=false
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - staticdeploy-postgres:/var/lib/postgresql

  minio:
    image: minio/minio
    restart: always
    labels:
      - traefik.enable=false
    environment:
      MINIO_ACCESS_KEY: $MINIO_ACCESS_KEY
      MINIO_SECRET_KEY: $MINIO_SECRET_KEY
    volumes:
      - staticdeploy-minio:/var/lib/minio
    command: server /var/lib/minio

  traefik:
    image: traefik:v1.7
    restart: always
    depends_on:
      - staticdeploy
    labels:
      - traefik.enable=false
    command: >-
      -c /dev/null --web
      --docker --docker.domain=$MANAGEMENT_HOSTNAME --docker.watch
      --entryPoints='Name:http Address::80'
      --entryPoints='Name:https Address::443 TLS'
      --acme --acme.email=$LE_EMAIL --acme.storage=/etc/traefik/acme/acme.json --acme.httpChallenge.entryPoint=http --acme.entryPoint=https --acme.domains=$MANAGEMENT_HOSTNAME
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - acme:/etc/traefik/acme
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  staticdeploy-postgres:
    external:
      name: staticdeploy-postgres
  staticdeploy-minio:
    external:
      name: staticdeploy-minio
  acme: {}
```

with env variables defined in a `.env` file like:

```sh
STATICDEPLOY_VERSION=v0.15.2
MANAGEMENT_HOSTNAME=my.domain.com
JWT_SECRET_OR_PUBLIC_KEY=my_secret # random string you generate
OIDC_CONFIGURATION_URL=https://my.oidc.provider/.well-known/openid-configuration
OIDC_CLIENT_ID=my_client_id
OIDC_PROVIDER_NAME=My Oidc Provider
LE_EMAIL=my.email.for.letsencrypt@domain.com
MINIO_ACCESS_KEY=my_minio_access_key # random string you generate
MINIO_SECRET_KEY=my_minio_secret_key # random string you generate
POSTGRES_PASSWORD=my_postgres_password # random string you generate
```

The configuration also sets up https for `MANAGEMENT_HOSTNAME`, getting certificates via Let's Encrypt. If you want to use https for sites you deploy on that instance of StaticDeploy, you need to tweak the traefik configuration a bit, at least adding the domains of the sites to `acme.domains`, but maybe something else is needed (I put a CDN in front of the sites, which provides https "higher up" the stack). The latest version of traefik (v2.x) changes how you configure it, and I haven't gotten around yet to update, so this docker compose configuration still uses v1.

**Comment by brumar** [comment]
Thanks a lot for sharing. That helped ! I had few hiccups with this docker-compose.yaml, so I thought I should share my version in case people got into the same troubles.
```
version: "3"
services:
  staticdeploy:
    image: staticdeploy/staticdeploy:$STATICDEPLOY_VERSION
    restart: always
    depends_on:
      - postgres
      - minio
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=HostRegexp:{host:.*}
      - traefik.frontend.passHostHeader=true
      - traefik.frontend.entryPoints=http,https
    environment:
      - MANAGEMENT_HOSTNAME=$MANAGEMENT_HOSTNAME
      - JWT_SECRET_OR_PUBLIC_KEY=$JWT_SECRET_OR_PUBLIC_KEY
      - OIDC_CONFIGURATION_URL=$OIDC_CONFIGURATION_URL
      - OIDC_CLIENT_ID=$OIDC_CLIENT_ID
      - OIDC_PROVIDER_NAME=$OIDC_PROVIDER_NAME
      - POSTGRES_URL=postgres://postgres:$POSTGRES_PASSWORD@postgres/postgres
      - S3_BUCKET=staticdeploy
      - S3_ENDPOINT=http://minio:9000
      - S3_ACCESS_KEY_ID=$MINIO_ACCESS_KEY
      - S3_SECRET_ACCESS_KEY=$MINIO_SECRET_KEY
  postgres:
    image: postgres
    restart: always
    labels:
      - traefik.enable=false
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - ./data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    restart: always
    labels:
      - traefik.enable=false
    environment:
      MINIO_ACCESS_KEY: $MINIO_ACCESS_KEY
      MINIO_SECRET_KEY: $MINIO_SECRET_KEY
    volumes:
      - ./staticdeploy-minio:/var/lib/minio
    command: server /var/lib/minio

  traefik:
    image: traefik:v1.7
    restart: always
    depends_on:
      - staticdeploy
    labels:
      - traefik.enable=false
    command: >-
      -c /dev/null --web
      --docker --docker.domain=$MANAGEMENT_HOSTNAME --docker.watch
      --entryPoints='Name:http Address::80'
      --entryPoints='Name:https Address::443 TLS'
      --acme --acme.email=$LE_EMAIL --acme.storage=/etc/traefik/acme/acme.json --acme.httpChallenge.entryPoint=http --acme.entryPoint=https --acme.domains=$MANAGEMENT_HOSTNAME
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - ./acme:/etc/traefik/acme
      - /var/run/docker.sock:/var/run/docker.sock
```
I tweaked a bit the volumes declaration because docker-compose complained about volumes being external, and postgresql volume did not persist on my VM (why my change worked? I don't know). Last important thing, I launched the whole thing with an unsophisticated `docker-compose up -d postgres && sleep 30 && docker-compose up -d`. Postgres needed some time to get ready before being asked by the application to perform migrations (it took me time to realize that that was the source of the crash).
