### ISSUE TITLE
Cross-origin request blocked when attempting OpenID connect authorization

### ISSUE THREAD

**Issue by ptwales** [staticdeploy/staticdeploy#72]
When trying to login with using Gitlab as an [OpenID Connect Provider](https://staticdeploy.io/docs/guides-openid-connect-providers), staticdeploy will replace the "Login with Gitlab" button with a network error message and the following error will be in the console.

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://gitlab.com/.well-known/openid-configuration.
(Reason: CORS header ‘Access-Control-Allow-Origin’ missing)
```

When I deliberately mis-configure the `OIDC_CONFIGURATION_URL` variable so that it would 404 I still get the same error.  So I don't believe it's an issue with Gitlab.

This is the docker-compose file that I'm using.
```
version: '3'

services:
  staticdeploy:
    image: staticdeploy/staticdeploy
    ports:
      - 80:80
    environment:
      MANAGEMENT_HOSTNAME: local.staticdeploy.io
      OIDC_CLIENT_ID: $OIDC_CLIENT_ID
      OIDC_CONFIGURATION_URL: https://gitlab.com
      OIDC_PROVIDER_NAME: GitLab
```
